main: com.gmail.thegeekedgamer.slashftop.FTopPlugin
name: SlashFTop
version: 1.0
api-version: 1.21
author: BadgersMC
description: A plugin that extends rosestacker to provide stacked spawner/block based Faction top system
depend:
  - RoseStacker
softdepend:
  - ShopGUIPlus
commands:
  ftop:
    description: Show a Ftop leaderboard
    usage: "/ftop <page>"
    aliases: ftop
permissions:
  ftop.base:
    description: Default perms
    default: true
  ftop.admin:
    description: Grants all other permissions
    default: false
    children:
      ftop.base: true
